const titles={overview:'نظرة عامة',products:'المنتجات والربحية',inventory:'المخزون والمشتريات',payroll:'الموظفون والرواتب',reports:'التقارير'};
const config={url:'https://wdzgwaeypxvjizageueu.supabase.co',key:'sb_publishable_jE3dU62W7kl2ffOBf0qMqg_Pb3wvOew'};
const localKey='cafemargin-credentials';
const saved=JSON.parse(localStorage.getItem(localKey)||'null')||{username:'admin',password:'1234'};
let cloudSession=JSON.parse(localStorage.getItem('cafemargin-session')||'null');
let shopId=localStorage.getItem('cafemargin-shop-id');
let userRole='';
const toast=document.querySelector('#toast');
function show(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
async function api(path,options={}){const headers={'apikey':config.key,'Content-Type':'application/json',...(options.headers||{})};if(cloudSession?.access_token)headers.Authorization=`Bearer ${cloudSession.access_token}`;const response=await fetch(`${config.url}/rest/v1/${path}`,{...options,headers});const text=await response.text();if(!response.ok){const message=text&&text.trim()?text:`Request failed: ${response.status}`;throw new Error(message)};if(response.status===204||!text.trim())return null;try{return JSON.parse(text)}catch{return text}}
async function auth(email,password){const response=await fetch(`${config.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!response.ok)throw new Error('بيانات الحساب السحابي غير صحيحة');cloudSession=await response.json();localStorage.setItem('cafemargin-session',JSON.stringify(cloudSession));return cloudSession}
async function ensureShop(){if(shopId)return shopId;const members=await api(`shop_members?user_id=eq.${cloudSession.user.id}&select=shop_id,role&limit=1`);if(members[0]){shopId=members[0].shop_id;userRole=members[0].role||'';localStorage.setItem('cafemargin-shop-id',shopId);return shopId}const shops=await api('shops',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({owner_id:cloudSession.user.id,name:'مقهى جديد',currency:'SAR'})});shopId=shops[0].id;userRole='owner';await api('shop_members',{method:'POST',body:JSON.stringify({shop_id:shopId,user_id:cloudSession.user.id,role:'owner'}));localStorage.setItem('cafemargin-shop-id',shopId);return shopId}
async function cloudList(table){if(!cloudSession)return[];await ensureShop();return api(`${table}?shop_id=eq.${shopId}&select=*`)}
async function setupSalesRole(){if(userRole!=='sales')return;document.querySelectorAll('[data-view]').forEach(button=>{button.hidden=button.dataset.view!=='sales'});document.querySelectorAll('.view').forEach(view=>{view.hidden=view.id!=='sales'});const salesView=document.createElement('section');salesView.id='sales';salesView.className='view active';salesView.innerHTML='<div class="section-head"><div><small>واجهة موظف المبيعات</small><h2>تسجيل بيع</h2><p>اختر المنتج والكمية لتسجيل عملية البيع.</p></div></div><div class="panel sales-panel"><form id="sales-form"><label>المنتج<select id="sale-product" required><option value="">اختر منتجًا</option></select></label><label>الكمية<input id="sale-quantity" type="number" min="1" value="1" required></label><button class="primary" type="submit">تسجيل البيع</button></form><p id="sales-message" class="cloud-note"></p><h3>عمليات اليوم</h3><div id="sales-today"></div></div>';document.querySelector('main')?.appendChild(salesView);const products=await cloudList('products');const select=salesView.querySelector('#sale-product');products.forEach(product=>{const option=document.createElement('option');option.value=product.id;option.textContent=`${product.name||'منتج'} - ${Number(product.sale_price||0).toFixed(2)} ر.س`;option.dataset.name=product.name||'منتج';select.appendChild(option)});const salesKey=`cafemargin-sales-${shopId}`;const renderSales=()=>{const sales=JSON.parse(localStorage.getItem(salesKey)||'[]').filter(sale=>sale.date===new Date().toISOString().slice(0,10));salesView.querySelector('#sales-today').innerHTML=sales.length?sales.map(sale=>`<p>${sale.name} × ${sale.quantity} <small>${sale.time}</small></p>`).join(''):'<p>لا توجد مبيعات اليوم.</p>'};salesView.querySelector('#sales-form').onsubmit=event=>{event.preventDefault();const option=select.selectedOptions[0];const quantity=Number(salesView.querySelector('#sale-quantity').value);if(!option?.value||quantity<1)return;const sales=JSON.parse(localStorage.getItem(salesKey)||'[]');sales.push({name:option.dataset.name,quantity,date:new Date().toISOString().slice(0,10),time:new Date().toLocaleTimeString('ar-SA')});localStorage.setItem(salesKey,JSON.stringify(sales));salesView.querySelector('#sales-message').textContent='تم تسجيل البيع';event.target.reset();salesView.querySelector('#sale-quantity').value=1;renderSales()};renderSales()}
function enforceRoleAccess(){if(userRole==='sales'){document.querySelectorAll('[data-view]').forEach(button=>button.hidden=button.dataset.view!=='sales');document.querySelectorAll('.view').forEach(view=>view.hidden=view.id!=='sales');document.querySelector('.settings')?.setAttribute('hidden','hidden');document.querySelector('#ask-ai')?.setAttribute('hidden','hidden');document.querySelector('#export')?.setAttribute('hidden','hidden')}}
async function loadCloudDashboard(){if(!cloudSession)return;try{const [shop,products,employees,ingredients]=await Promise.all([api(`shops?id=eq.${shopId}&select=name&limit=1`),cloudList('products'),cloudList('employees'),cloudList('ingredients')]);const shopName=shop?.[0]?.name||'محلي';const customerName=cloudSession.user?.user_metadata?.full_name||cloudSession.user?.email?.split('@')[0]||'المستخدم';const branch=document.querySelector('.branch b');const profile=document.querySelector('.profile strong');const welcome=document.querySelector('.welcome h2');if(branch)branch.textContent=shopName;if(profile)profile.textContent=customerName;if(welcome)welcome.innerHTML=`صباح الخير يا ${customerName} <span>☀</span>`;document.querySelectorAll('.kpi,.overview .grid,.summary,.report-cards,.report,.alerts,.supplies,.stock').forEach(element=>element.hidden=true);document.querySelectorAll('#products tbody,#payroll tbody').forEach(body=>{body.innerHTML='<tr><td colspan="6">لا توجد بيانات مسجلة بعد.</td></tr>'});const productList=document.querySelector('.products');if(productList)productList.innerHTML=products.length?products.map(product=>`<div><b class="pic mint">☕</b><p><strong>${product.name||'منتج'}</strong><small>${product.category||''}</small></p><strong class="margin">${Number(product.sale_price||0).toFixed(2)} <small>ر.س</small></strong></div>`).join(''):'<p class="cloud-note">لا توجد منتجات مسجلة بعد.</p>';const productRows=document.querySelector('#products tbody');if(productRows&&products.length)productRows.innerHTML=products.map(product=>`<tr><td><b>${product.name||'منتج'}</b><small>${product.category||''}</small></td><td>${Number(product.sale_price||0).toFixed(2)} ر.س</td><td>-</td><td>-</td><td>-</td><td><mark class="ok">مضاف</mark></td></tr>`).join('');const employeeRows=document.querySelector('#payroll tbody');if(employeeRows&&employees.length)employeeRows.innerHTML=employees.map(employee=>`<tr><td><b>${employee.name||'موظف'}</b></td><td>${employee.job_title||''}</td><td>${Number(employee.salary||0).toFixed(2)} ر.س</td><td>-</td><td>-</td><td>-</td></tr>`).join('');if(!ingredients.length)show('ابدأ بإضافة منتجات ومواد وموظفين لمحلّك')}catch(error){show('تعذر تحميل بيانات المحل')}}
function activate(view){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===view));document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));const title=document.querySelector('#title');if(title)title.textContent=titles[view];refresh(view);window.scrollTo({top:0,behavior:'smooth'})}
async function refresh(view){if(!cloudSession)return;try{if(view==='products')show('تم الاتصال: المنتجات محفوظة سحابيًا');if(view==='inventory')show('تم الاتصال: المخزون محفوظ سحابيًا');if(view==='payroll')show('تم الاتصال: الموظفون محفوظون سحابيًا')}catch(error){show('تعذر قراءة بيانات السحابة')}}
function addStyles(){const style=document.createElement('style');style.textContent='.cloud-note{display:block;color:#3c9674;font-size:10px;margin-top:8px}.cloud-error{display:block;color:#c95c54;font-size:11px;margin-top:8px}.cloud-button{background:#126d68!important;color:#fff!important}';document.head.appendChild(style)}
function showLogin(){document.querySelector('.shell').style.display='none';const overlay=document.createElement('section');overlay.className='auth-overlay';overlay.innerHTML='<div class="auth-card"><div class="auth-brand"><b>cm</b><strong>CafeMargin</strong></div><small class="auth-kicker">منصة إدارة ربحية المقاهي</small><h1>دخول آمن للمشروع</h1><p>استخدم بريد حساب Supabase للدخول من أي جهاز. الحساب المحلي القديم متاح كحل احتياطي.</p><form id="auth-form"><label>البريد الإلكتروني أو اسم المستخدم<input id="auth-user" autocomplete="username" required></label><label>الرقم السري<input id="auth-pass" type="password" autocomplete="current-password" required></label><button class="auth-submit">دخول إلى الحساب ←</button><small class="auth-error" id="auth-error"></small></form><small class="auth-hint">للدخول السحابي استخدم البريد المسجل في Supabase</small></div></section>';document.body.appendChild(overlay);const requestButton=document.createElement('button');requestButton.className='auth-submit cloud-button';requestButton.type='button';requestButton.textContent='إنشاء حساب جديد';requestButton.onclick=openAccessRequest;overlay.querySelector('.auth-card').appendChild(requestButton);document.querySelector('#auth-form').addEventListener('submit',async event=>{event.preventDefault();const user=document.querySelector('#auth-user').value.trim();const pass=document.querySelector('#auth-pass').value;const error=document.querySelector('#auth-error');try{if(user.includes('@')){await auth(user,pass);await ensureShop();await loadCloudDashboard();show('تم الدخول وحفظ بياناتك على السحابة')}else if(user===saved.username&&pass===saved.password){show('تم الدخول المحلي. استخدم بريد Supabase للمزامنة بين الأجهزة')}else throw new Error('بيانات الدخول غير صحيحة');overlay.remove();document.querySelector('.shell').style.display='flex';addLogoutButton()}catch(exception){error.textContent=exception.message}})}
function openAccessRequest(){const dialog=document.createElement('div');dialog.className='account-dialog';dialog.innerHTML='<form class="account-card" id="access-request-form"><h2>طلب حساب جديد</h2><p>سيُراجع طلبك قبل تفعيل الدخول إلى المحل.</p><label>البريد الإلكتروني<input id="request-email" type="email" required></label><label>الاسم الكامل<input id="request-name" required></label><label>اسم المحل<input id="request-shop" required></label><label>الصلاحية المطلوبة<select id="request-role"><option value="staff">موظف</option><option value="manager">مدير</option></select></label><small class="auth-error" id="request-error"></small><div class="account-actions"><button type="submit">إرسال الطلب</button><button type="button" id="cancel-request">إلغاء</button></div></form>';document.body.appendChild(dialog);document.querySelector('#cancel-request').onclick=()=>dialog.remove();document.querySelector('#access-request-form').onsubmit=async event=>{event.preventDefault();const error=document.querySelector('#request-error');const email=document.querySelector('#request-email').value.trim().toLowerCase();const fullName=document.querySelector('#request-name').value.trim();const shopName=document.querySelector('#request-shop').value.trim();const role=document.querySelector('#request-role').value;try{await api('access_requests',{method:'POST',body:JSON.stringify({email,full_name:fullName,shop_name:shopName,requested_role:role,status:'pending'})});const mail=await fetch('https://formsubmit.co/ajax/erthcafe11@gmail.com',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({_subject:'طلب تسجيل جديد في CafeMargin',_captcha:'false',email,الاسم:fullName,المحل:shopName,الصلاحية:role})});if(!mail.ok)throw new Error('تم حفظ الطلب لكن تعذر إرسال إشعار البريد');dialog.remove();show('تم حفظ الطلب وإرسال إشعار إلى بريد المالك')}catch(exception){error.textContent='تعذر إرسال الطلب: '+exception.message}}}
async function addRecord(kind){if(!cloudSession){show('سجّل ببريد Supabase أولًا لتفعيل الحفظ السحابي');return}await ensureShop();const definitions={product:{table:'products',fields:[['name','اسم المنتج'],['category','التصنيف'],['sale_price','سعر البيع']]},material:{table:'ingredients',fields:[['name','اسم المادة'],['unit','الوحدة'],['unit_cost','تكلفة الوحدة'],['current_quantity','الكمية الحالية'],['reorder_level','حد التنبيه']]},employee:{table:'employees',fields:[['name','اسم الموظف'],['job_title','الوظيفة'],['salary','الراتب']]}};const definition=definitions[kind];const record={shop_id:shopId};for(const [field,label]of definition.fields){const value=prompt(label);if(value===null)return;record[field]=['sale_price','unit_cost','current_quantity','reorder_level','salary'].includes(field)?Number(value)||0:value}await api(definition.table,{method:'POST',body:JSON.stringify(record)});show('تم الحفظ في قاعدة البيانات السحابية');refresh(document.querySelector('.view.active')?.id||'overview')}
function openAccount(){const user=prompt('اسم المستخدم المحلي الجديد',saved.username);if(!user)return;const password=prompt('الرقم السري المحلي الجديد، اتركه فارغًا للإبقاء عليه')||saved.password;localStorage.setItem(localKey,JSON.stringify({username:user,password}));show('تم تحديث الحساب المحلي. حساب Supabase يدار من إعدادات البريد')}
function logout(){localStorage.removeItem('cafemargin-session');localStorage.removeItem('cafemargin-shop-id');window.location.reload()}
function addLogoutButton(){if(document.querySelector('#logout'))return;const button=document.createElement('button');button.id='logout';button.className='settings';button.type='button';button.textContent='↪ تسجيل الخروج';button.onclick=logout;document.querySelector('.side-bottom')?.insertBefore(button,document.querySelector('.profile'))}
function hideDemoCards(){if(!cloudSession)return;document.querySelectorAll('.kpi,#overview .grid,.summary,.report-cards,.report,.alerts,.supplies,.stock').forEach(element=>element.style.setProperty('display','none','important'))}
setInterval(hideDemoCards,300);
setInterval(()=>{if(cloudSession&&userRole==='sales'&&!document.querySelector('#sales'))setupSalesRole()},500);
addStyles();
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>activate(button.dataset.view)));
document.querySelectorAll('.link').forEach(button=>button.addEventListener('click',()=>activate(button.dataset.view)));
document.querySelector('#ask-ai')?.addEventListener('click',()=>{activate('overview');document.querySelector('#question')?.focus();show('أدخل بياناتك السحابية ليحللها المستشار')});
document.querySelector('#review')?.addEventListener('click',()=>show('سيُحسب الاقتراح من بيانات المنتجات بعد ربط المبيعات الفعلية'));
document.querySelector('#send')?.addEventListener('click',()=>show(cloudSession?'سأحلل بيانات هذا المحل بعد تسجيل المبيعات':'سجّل دخول Supabase لقراءة بيانات المحل'));
document.querySelector('#export')?.addEventListener('click',()=>show('التصدير السحابي سيستخدم بيانات المحل الحالي'));
document.querySelector('.settings')?.addEventListener('click',openAccount);
document.querySelectorAll('.primary').forEach(button=>{const text=button.textContent;if(text.includes('إضافة منتج'))button.addEventListener('click',()=>addRecord('product'));if(text.includes('تسجيل توريد'))button.addEventListener('click',()=>addRecord('material'));if(text.includes('إضافة موظف'))button.addEventListener('click',()=>addRecord('employee'))});
if(cloudSession){document.querySelector('.shell').style.display='flex';addLogoutButton();shopId=null;ensureShop().then(loadCloudDashboard).then(setupSalesRole).catch(()=>show('تعذر استعادة جلسة السحابة'))}else showLogin();